---
services:
  unifi-voucher-manager:
    image: "docker.io/etiennecollin/unifi-voucher-manager:latest"
    # Or use the github registry
    # image: "ghcr.io/etiennecollin/unifi-voucher-manager:latest"

    # To build the image yourself
    # build:
    #   context: "./"
    #   target: "runtime"
    #   dockerfile: "./Dockerfile"

    container_name: "unifi-voucher-manager"
    restart: "unless-stopped"
    ports:
      - "3000:3000"

    # Display your custom SVG logo. The mount destination CANNOT BE CHANGED.
    # volumes:
    #   - "./assets/my_logo.svg:/app/frontend/public/logo.svg"

    # SEE README FOR ENVIRONMENT VARIABLES DOCUMENTATION
    environment:
      UNLEASHED_URL: "https://unleashed.example.com"
      UNLEASHED_USERNAME: "guestpass"
      UNLEASHED_PASSWORD: "changeme"
      UNLEASHED_SSID: "Guest"
      UNLEASHED_HAS_VALID_CERT: "true"
      TIMEZONE: "UTC"
      DAILY_ROLL_HOUR: "4"
      DAILY_DURATION_HOURS: "24"
      DAILY_SHARE_NUMBER: "0"
      WIFI_SSID: "Guest"
      WIFI_PASSWORD: ""
