---
services:
  unleashed-voucher-manager:
    image: "ghcr.io/greyrock-labs/unleashed-voucher-manager:latest"

    # To build the image yourself
    # build:
    #   context: "./"
    #   target: "runtime"
    #   dockerfile: "./Dockerfile"

    container_name: "unleashed-voucher-manager"
    restart: "unless-stopped"
    ports:
      - "3000:3000"

    # Display your custom SVG logos. The mount destinations CANNOT BE CHANGED.
    # volumes:
    #   - "./assets/my_logo.svg:/app/frontend/public/logo.svg"
    #   - "./assets/my_qr_logo.svg:/app/frontend/public/qr-logo.svg"

    # SEE README FOR ENVIRONMENT VARIABLES DOCUMENTATION
    environment:
      UNLEASHED_URL: "URL of your Unleashed controller with protocol (`https://`)."
      UNLEASHED_USERNAME: "Controller user whose role has read-write admin privilege."
      UNLEASHED_PASSWORD: "Password for that user."
      UNLEASHED_SSID: "The guest WLAN that vouchers are created on."
      UNLEASHED_HAS_VALID_CERT: "true" # Set to false only if the controller serves a self-signed certificate.
      WIFI_SSID: "Your guest WiFi SSID" # Optional, but recommended
      WIFI_PASSWORD: "Your guest WiFi password" # Optional, but recommended
      GUEST_SUBNETWORK: "Your guest subnetwork in IPv4 CIDR notation (X.X.X.X/X)" # Optional, but recommended
      TIMEZONE: "Your timezone (America/Toronto)" # Optional, but recommended
