---
services:
  unifi-voucher-manager:
    image: "docker.io/etiennecollin/unifi-voucher-manager:latest"
    # Or use the github registry
    # image: "ghcr.io/etiennecollin/unifi-voucher-manager:latest"

    # To build the image yourself
    # build:
    #   context: "./"
    #   target: "runtime"
    #   dockerfile: "./Dockerfile"

    container_name: "unifi-voucher-manager"
    restart: "unless-stopped"
    ports:
      - "3000:3000"

    # Display your custom SVG logo. The mount destination CANNOT BE CHANGED.
    # volumes:
    #   - "./assets/my_logo.svg:/app/frontend/public/logo.svg"

    # SEE README FOR ENVIRONMENT VARIABLES DOCUMENTATION
    environment:
      UNIFI_CONTROLLER_URL: "URL to your UniFi controller with protocol (`http://` or `https://`)."
      UNIFI_API_KEY: "API Key for your UniFi controller."
      UNIFI_HAS_VALID_CERT: "true" # Set to false only if your UniFi controller does not use a valid SSL certificate. Typically, this should remain true when accessing the controller (UNIFI_CONTROLLER_URL) through a reverse proxy or any setup providing trusted SSL certificates (e.g., Let's Encrypt).
      WIFI_SSID: "Your guest WiFi SSID" # Optional, but recommended
      WIFI_PASSWORD: "Youw guest WiFi password" # Optional, but recommended
      GUEST_SUBNETWORK: "Your guest subnetwork in IPv4 CIDR notation (X.X.X.X/X)" # Optional, but recommended
      TIMEZONE: "Your timezone (America/Toronto)" # Optional, but recommended
